### ISSUE TITLE
Problem with linux script (debian 9)

### ISSUE THREAD

**Issue by CheckB** [asand3r/zbx-hpsmartarray#7]
```
 ./zbx-hpsmartarray.py 
Traceback (most recent call last):
  File "./zbx-hpsmartarray.py", line 254, in <module>
    sys.exit(main(action, ctrlid, part, partid))
  File "./zbx-hpsmartarray.py", line 213, in main
    ssacli = get_ssacli()
  File "./zbx-hpsmartarray.py", line 207, in get_ssacli
    if os.path.isfile(fpath) and os.access(fpath, os.X_OK):
NameError: global name 'os' is not defined
```

`import os` ?

**Comment by CheckB** [comment]
```
Example 3: Health of physical drive 
$ ./zbx-hpsmartarray.py -a lld -p pd -c
```

option -c requires argument

**Comment by CheckB** [comment]
```
Example 2: Health of logical drive
$ ./zbx-hpsmartarray.py -a health -p ld -c 0 -i 1
```

UNKNOWN

**Comment by CheckB** [comment]
@asand3r 
In general... the script executes correctly. All you need is documentation for Linux. You have the only current project for HPE SmartArray. At least I hope so.
