### ISSUE TITLE
NameError: global name 'os' is not defined

### ISSUE THREAD

**Issue by tdslot** [asand3r/zbx-hpsmartarray#9]
```
root@mon01:~/zbx-hpsmartarray-master# ./zbx-hpsmartarray.py -a lld -p ctrl
Traceback (most recent call last):
  File "./zbx-hpsmartarray.py", line 254, in <module>
    sys.exit(main(action, ctrlid, part, partid))
  File "./zbx-hpsmartarray.py", line 213, in main
    ssacli = get_ssacli()
  File "./zbx-hpsmartarray.py", line 207, in get_ssacli
    if os.path.isfile(fpath) and os.access(fpath, os.X_OK):
NameError: global name 'os' is not defined
```

Please modify python script `zbx-hpsmartarray.py` add

`import os`

It will fix this problem.

**Comment by asand3r** [comment]
Yeah, sorry ) totally haven't time too work with it. =D Added needed import in 0.4.7 branch, merged to master.
